### PR TITLE
support for prefix option

### PR DESCRIPTION
**Pull request by rqrqrqrq**

### CODE REVIEW

**Comment by mslipper** [comment]
Thanks for doing this! Let me know when you're ready and I'll review.

**Comment by mslipper** [comment]
@rqrqrqrq is this guy ready?

**Comment by rqrqrqrq** [comment]
@mslipper Not yet 🌚Hope i'll finish this in the weekend. Sorry for the delay

**Comment by rqrqrqrq** [comment]
@mslipper Think im ready now. Still want to add tests for `handleActions` (even if all related changes covered in `flattenUtils` tests) but i guess it can be verified separately.

**Comment by rqrqrqrq** [comment]
TODO:
- [ ] Tests for handeActions
- [ ] Update docs (?)

**Comment by victordidenko** [comment]
I would really love to see this PR merged 😍

**Comment by mslipper** [comment]
I'll review today. Totally missed the notification.

**Comment by mslipper** [comment]
LGTM!

**Comment by victordidenko** [comment]
@mslipper Do you know about plans to draft new release any time soon? Last one was more than half year ago already...

**Comment by mslipper** [comment]
I can do a release tonight.

**Comment by victordidenko** [comment]
That would be supercool 👍

**Comment by nmaves** [comment]
Looks like the docs still need updating.

**Pull request merged**
